name: drc

on:
  push:
  workflow_dispatch:

jobs:
  drc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: checkout PDK
        uses: actions/checkout@v4
        with:
          repository: IHP-GmbH/IHP-Open-PDK
          path: 'pdk'


      - name: Install KLayout
        run: |
          wget https://www.klayout.org/downloads/Ubuntu-22/klayout_0.29.4-1_amd64.deb
          sudo apt-get install -y ./klayout_0.29.4-1_amd64.deb
      
      - name: Run DRC
        run: |
          klayout -b -r ./pdk/ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2.lydrc -rd cell=ttsimon ./results/ihp-sg13g2/ttsimon/base/6_final.gds

      - name: Upload DRC results
        uses: actions/upload-artifact@v4
        with:
          name: drc-results
          path: sg13g2_ttsimon.lyrdb

          